### ISSUE TITLE
No espacio con escesivos BR

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-chattas#3]
https://github.com/UCC-LabCompu2/proyecto2022-chattas/blob/bb259816712c1de8ca155cceafef562e98efdfed/graficador.html#L52-L76

Se recomienda emplear los inputs agrupados por `<p>` o `<div>`. Por ejemplo:
`````
<p>
        <label for="angulo">Ángulo:</label>
        <input type="number" id="angulo" readonly>º
</p>
``````

y en todo caso, agregar a esos `<p>` o `<div>` margin

**Comment by MaximoChattas** [comment]
Solucionado
