### ISSUE TITLE
Luego de llenar los campos con valores incorrectos, y presionar Graficar, la línea sigue dibujada

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-chattas#4]
![imagen](https://user-images.githubusercontent.com/8345007/173240003-9a2e96fe-0493-45e7-9079-781459386ebc.png)

**Comment by MaximoChattas** [comment]
Elimino verificación OnChange. Verifica datos onclick de graficar para mejorar experiencia de usuario. Si los datos ingresados no son válidos, elimina la recta dibujada y los datos en información sobre función
