### ISSUE TITLE
Valores fuera de rango

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-chattas#5]
No debería permitir al usuario ingresar valores que queden fuera del rango de dibujo (ó, en caso de permitirlo, indicar que la gráfica no se realizará porque está fuera de rango).
Además, no deberían quedar números superpuestos (ver imagen adjunta)
![imagen](https://user-images.githubusercontent.com/8345007/173240091-a5fef1b5-1b85-4039-8b04-996c986ed6a5.png)

Se sugiere no permitir más de 2 decimales (por lo menos para mostrar el resultado):
![imagen](https://user-images.githubusercontent.com/8345007/173240258-77d79b27-32ff-4d6c-9361-11560c4a8d5f.png)

**Comment by MaximoChattas** [comment]
Aumento tamaño de Span. 
Verifica que los valores ingresados se encuentren en el intervalo [-15 ; 15] para que el gráfico se vea correctamente.
