### ISSUE TITLE
Si se ingresa una pendiente 0, el valor de Y es constante (en lugar de mostrar mensaje de error, debería msotrarse una línea horizontal)

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-chattas#7]
![imagen](https://user-images.githubusercontent.com/8345007/174499596-727ec27f-fce9-4435-93df-a293f1c64a58.png)

**Comment by MaximoChattas** [comment]
Agrego opción para graficar función constante.
